micronaut:
  application:
    name: imgmani
datasources:
  default:
    url: jdbc:postgresql://localhost:5433/person-db
    username: person-admin
    password: "sa"
    driverClassName: org.postgresql.Driver
  test:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver
flyway:
  datasources:
    default:
      locations: classpath:db/migrations
